[tool.poetry]
name = "ayautils"
version = "0.2.1"
description = ""
authors = ["martinjose <josemartin90@gmail.com>"]
readme = "README.md"
packages = [{include = "ayautils", from = "src"}]

[tool.poetry.dependencies]
python = "^3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
